name: Sync
on:
  push:
    branches:
    # Change this to whatever branch you want this action to trigger on.
    # Ideally it should match the "FROM_BRANCH" setting below.
      - main

permissions:
  # Needed to read branches
  contents: read
  # Needed to create PR's
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: jdtx0/branch-sync@1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_AUTO_MERGE_METHOD: 'merge'
