on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"

      - name: make deploy keys
        env:
          GH_DEPLOY_KEY: ${{ secrets.ACTION_SECRET }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Sync Branch
        uses: remarkablemark/sync-branch@v1
        with:
          base: develop
          token: ${{ secrets.GITHUB_TOKEN }}
